### ISSUE TITLE
Build Of Linux

### ISSUE THREAD

**Issue by gvsurenderreddy** [mjmunger/BYOLMI#4]
Hello Sir,
It would been nice if u can provide with linux as well i386 

Thanks again for window build

**Comment by mjmunger** [comment]
There are a few components in this package. tinc (available on all major distros) and a VNC installer (ultra vnc from uvnc.com).

If you want to do this for Linux, you would still setup tinc as normal, and then use a different vnc viewer like x11vnc.

What, specifically can I help you with?

**Comment by gvsurenderreddy** [comment]
Hello sir,
I want similar setup for Linux instead of buying Teamviewer Lisence for
systems behind nat.

**Comment by mjmunger** [comment]
On client Linux machines:
apt-get install tinc
apt-get install x11vnc

Then, you'll need to follow this: http://learnlinuxonline.com/servers/setting-up-a-vpn-with-tinc-vpn-software

To make this work you need a central node they can all connect back to. For us, we have a public IP it works on. You could (maybe) do it with dynamic DNS, but I have never tried it.

**Comment by gvsurenderreddy** [comment]
Yes we have Several Server With Public IPS from Digitalocean and others.You
have done simple sets to make these things faster my question instead of
doing all these u have anything for linux as well.I have over 100 Clients
on Linux wanted something alternative than team viewer .Thanks
